
import prisma from "@/lib/prisma";
import { hash } from "bcryptjs";
import { Prisma } from "@prisma/client";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const username = body?.username?.toString().trim();
    const email = body?.email?.toString().trim().toLowerCase();
    const password = body?.password?.toString();

    // Field required validation
    if (!username || !email || !password) {
      return NextResponse.json({ error: "Username, email and password are required" }, { status: 400 });
    }

    // Encrypting the password using bcrypt hash function
    const hashedPassword = await hash(password, 10);
    // creating the user user prisma.user.create
    const user = await prisma.user.create({
      data: {
        username,
        email,
        password: hashedPassword,
        role: "USER", // Explicitly set role; super admin can change the role afterwards
        isVerified: false, // Default until approved by super admin
      },
    });
    // success response
    return NextResponse.json(
      {
        message: "Account created successfully",
        user: {
          id: user.id,
          username: user.username,
          email: user.email,
          role: user.role,
          isVerified: user.isVerified,
        },
      },
      { status: 201 }
    );
  } catch (error: unknown) {
    console.log(error);
    // Handle unique constraint violation (email/username), P2002 is a code generated by prisma
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") {
      return NextResponse.json(
        { error: "Username or email already exists" },
        { status: 409 }
      );
    }
    // Internal server error
    return NextResponse.json(
      { error: "Failed to create user" },
      { status: 500 }
    );
  }
}
